---
# tasks file for mysql
    - name: 'install mysql & python3 for mysql packages'
      apt:
        force_apt_get: true
        update_cache: true
        name: '{{item}}'
        state: 'present'
      become: true
      loop: '{{program_list}}'
    - name: 'Create a new database with name wordpress_db'
      community.mysql.mysql_db:
        login_unix_socket: '{{mysql_unixsocket_path}}'
        name: '{{db_name}}'
        state: 'present'
      become: true
    - name: 'Create db user pass'
      community.mysql.mysql_user:
        login_unix_socket: '{{mysql_unixsocket_path}}'
        name: '{{uname}}'
        password: '{{upass}}'
        priv: '*.*:ALL,GRANT'
      become: true

